const fruitsMenu = [
  {
    id: 1,
    image: "mango.jfif",
    name: "Mango",
    season: "Summer",
    price: 80,
    description: "Sweet and juicy, King of fruits, Summer Special",
  },
  {
    id: 2,
    image: "orange.jfif",
    name: "Orange",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
  {
    id: 3,
    image: "pomengrates.jfif",
    name: "Pomegranate",
    season: "Automn",
    price: 120,
    description: "Sweet and juicy, Automn fruit",
  },
  {
    id: 4,
    image: "lemon.jfif",
    name: "Lemon",
    season: "Autumn",
    price: 10,
    description: "Sweet and juicy, Autumn fruit",
  },
  {
    id: 5,
    image: "watermelon.jfif",
    name: "Watermelon",
    season: "Summer",
    price: 80,
    description: "Sweet and juicy, Summer Special",
  },
  {
    id: 6,
    image: "jamun.jfif",
    name: "Jamun",
    season: "Summer",
    price: 80,
    description: "Sweet and juicy, Summer Special",
  },
  {
    id: 7,
    image: "papaya.jfif",
    name: "Papaya",
    season: "Summer",
    price: 80,
    description: "Sweet and juicy, Summer Special",
  },
  {
    id: 8,
    image: "lychee.jfif",
    name: "Lychee",
    season: "Summer",
    price: 200,
    description: "Sweet and juicy, Summer Special",
  },
  {
    id: 9,
    image: "plum.jfif",
    name: "Plum",
    season: "Summer",
    price: 80,
    description: "Sweet and juicy, Summer Special",
  },
  {
    id: 10,
    image: "apple.jfif",
    name: "Apple",
    season: "Rainy",
    price: 80,
    description: "Sweet and juicy, Mansoon/Rainy Special",
  },
  {
    id: 11,
    image: "figs.jfif",
    name: "Figs",
    season: "Autumn",
    price: 50,
    description: "Sweet and juicy, Autumn fruit",
  },
  {
    id: 12,
    image: "passion.jfif",
    name: "Passion ( कृष्णा फल )",
    season: "Autumn",
    price: 50,
    description: "Sweet and juicy, Autumn fruit",
  },
  {
    id: 13,
    image: "pear.jfif",
    name: "Pear",
    season: "Rainy",
    price: 80,
    description: "Sweet and juicy, Mansoon/Rainy Special",
  },
  {
    id: 14,
    image: "cherry.jfif",
    name: "Cherry",
    season: "Rainy",
    price: 80,
    description: "Sweet and juicy, Mansoon/Rainy Special",
  },
  {
    id: 15,
    image: "guava.jfif",
    name: "Guava",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
  {
    id: 16,
    image: "strawberry.jfif",
    name: "Strawberry",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
  {
    id: 17,
    image: "grapes.jfif",
    name: "Grapes",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
  {
    id: 18,
    image: "kiwi.jfif",
    name: "Kiwi",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
  {
    id: 19,
    image: "pineapple.jfif",
    name: "Pineapple",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
  {
    id: 20,
    image: "banana.jfif",
    name: "Banana",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
  {
    id: 21,
    image: "c_apple.jfif",
    name: "Custurd Apple",
    season: "Winter",
    price: 180,
    description: "Sweet and juicy, It is a Winter fruit",
  },
];
export default fruitsMenu 